---
- name: reload supervisor conf
  supervisorctl: "name=gunicorn_mezzanine state=present"
  become: True
- name: restart supervisor
  supervisorctl: name=gunicorn_mezzanine state=restarted
  become: True
- name: restart nginx
  service: name=nginx state=restarted
  become: True
